name: Build .jar file

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build with Gradle
      run: ./gradlew build

    - name: Upload .jar as artifact
      uses: actions/upload-artifact@v2
      with:
        name: jar-file
        path: build/libs/*.jar
